services:
  - type: worker
    name: gebiplus-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MEDIA_GROUP_DELAY
        value: 3.5
      - key: DB_PATH
        value: /data/bot.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
